---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  type: ClusterIP
  clusterIP: 10.43.1.32
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr