apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-sync
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  storageClassName: harvester  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs  
