apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: ClusterIP
  clusterIP: 10.43.1.81
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui