apiVersion: v1
kind: Service
metadata:
  name: lidarr-proxy
spec:
  type: ClusterIP
  clusterIP: 10.43.1.34
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: lidarr-proxy
    app.kubernetes.io/instance: lidarr-proxy
