# nextcloud PVC for config
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: nextcloud-db
  labels:
    app.kubernetes.io/name: nextcloud-db
    app.kubernetes.io/instance: nextcloud-db
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  storageClassName: harvester
---