apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  annotations:
  labels:
    app.kubernetes.io/name: nextcloud-db
    app.kubernetes.io/instance: nextcloud-db
spec:
  type: ClusterIP
  clusterIP: 10.43.1.61
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: nextcloud-db
    app.kubernetes.io/instance: nextcloud-db