apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1                 # The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 2           # The number of pods that can be unavailable during the update process
    type: RollingUpdate           # New pods are added gradually, and old pods are terminated gradually
  replicas: 3 
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-db
      app.kubernetes.io/instance: nextcloud-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-db
        app.kubernetes.io/instance: nextcloud-db
    spec:
      containers:
        - name: nextcloud-db
          image: "postgres:15.7-bookworm"
          command:
            - postgres
            - -c
            - listen_addresses="*"
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: db_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: db_name
          volumeMounts: 
            - name: nextcloud
              mountPath: "/var/lib/postgresql/data"
              subPath: postgres
        - name: redis
          image: redis:7.4.0
          ports: 
            - containerPort: 6379
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud