apiVersion: v1
kind: Service
metadata:
  name: node-red
  labels:
    app.kubernetes.io/name: node-red
    app.kubernetes.io/instance: node-red
spec:
  type: ClusterIP
  clusterIP: 10.43.1.42
  ports:
    - port: 1880
      targetPort: 1880
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: node-red
    app.kubernetes.io/instance: node-red
---