apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: guacamole
      app.kubernetes.io/instance: guacamole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guacamole
        app.kubernetes.io/instance: guacamole
    spec:
      containers:
        - name: guacamole
          image: flcontainers/guacamole:1.5.5
          env:
            - name: EXTENSIONS
              value: "auth-header"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/config"
              name: guacamole
      volumes:
        - name: guacamole
          persistentVolumeClaim:
            claimName: guacamole
---
