apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-lb
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole