apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
spec:
  type: ClusterIP
  clusterIP: 10.43.1.33
  ports:
    - port: 9696
      targetPort: 9696
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/instance: prowlarr
