apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  labels:
    app.kubernetes.io/name: immich-redis
    app.kubernetes.io/instance: immich-redis
spec:
  type: ClusterIP
  clusterIP: 10.43.1.47
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: immich-redis
    app.kubernetes.io/instance: immich-redis
