apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-addons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: nfs  
---