apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi
  storageClassName: harvester  
---