apiVersion: v1
kind: Service
metadata:
  name: immich-ml
  labels:
    app.kubernetes.io/name: immich-ml
    app.kubernetes.io/instance: immich-ml
spec:
  type: ClusterIP
  clusterIP: 10.43.1.45
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: immich-ml
    app.kubernetes.io/instance: immich-ml
