apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-cron
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-cron
      app.kubernetes.io/instance: nextcloud-cron
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-cron
        app.kubernetes.io/instance: nextcloud-cron
    spec:
      containers:
        # cronjob container
        - name: cron
          image: nextcloud:29.0.6
          command: ["/cron.sh"]
          
          # Update crontab on startup
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "echo '*/5 * * * * php /var/www/nextcloud/occ preview:pre-generate' >> /var/spool/cron/crontabs/www-data"
          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud
              subPath: app
            - mountPath: "/var/www/html/data"
              name: nextcloud-data
              subPath: userdata
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/nextcloud
