apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
    spec:
      containers:
        # Nextcloud container
        - name: nextcloud
          image: nextcloud:29.0.6
          ports:
            - containerPort: 80
          env: 
            # DB config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: db_name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: db_password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: db_user
                  
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: db_host

            # Redis config
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: redis_host

            # App config
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: nextcloud
                  key: admin

            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: admin_password

            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: trusted_domains

            # Force nextcloud to respond to HTTPS only
            - name: OVERWRITEPROTOCOL
              value: "https"
            # Runs occ maintenance:update:htaccess after container initialization
            - name: NEXTCLOUD_INIT_HTACCESS
              value: "true"

            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8
            # Increase the PHP memory limit

            - name: PHP_MEMORY_LIMIT 
              value: 8G
            # Needed for larger file uploads
            - name: PHP_UPLOAD_LIMIT 
              value: 500G

            # Needed to prevent 413s with large files
            - name: APACHE_BODY_LIMIT
              value: "0" # 0 is unlimited!

            # Email SMTP config
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: smtp_host
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURE
              value: "tls"
            - name: SMTP_NAME
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: smtp_username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: smtp_password
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: smtp
                  key: mail_from_address
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"

          volumeMounts:
            - mountPath: "/var/www/html"
              name: nextcloud
              subPath: app
            - mountPath: "/var/www/html/data"
              name: nextcloud-data
              subPath: userdata
          
          # Install dependencies for SMB
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", "apt-get update && apt-get install -y procps smbclient && rm -rf /var/lib/apt/lists/*"]
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nextcloud-data
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/nextcloud
