# nextcloud PVC for config
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "40Gi"
  storageClassName: harvester
---