apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      # I think this will allow Home Assistant to more easily communicate with the smart devices?
      hostNetwork: true
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.10.4
          ports:
            - containerPort: 8123
            - containerPort: 1400
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant
            - mountPath: "/config/configuration.yaml"
              name: home-assistant-config
              subPath: configuration.yaml
      volumes:
        - name: home-assistant
          persistentVolumeClaim:
            claimName: home-assistant
        - name: home-assistant-config
          configMap:
            name: home-assistant-config
---