apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 0           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: home-assistant
    spec:
      # I think this will allow Home Assistant to more easily communicate with the smart devices?
      hostNetwork: true
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.11.0
          ports:
            - containerPort: 8123
            - containerPort: 1400
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant
            - mountPath: "/config/configuration.yaml"
              name: home-assistant-config
              subPath: configuration.yaml
      volumes:
        - name: home-assistant
          persistentVolumeClaim:
            claimName: home-assistant
        - name: home-assistant-config
          configMap:
            name: home-assistant-config
---