apiVersion: v1
kind: Service
metadata:
  name: home-assistant-discovery
  
  labels:
    app.kubernetes.io/name: home-assistant0-discovery
    app.kubernetes.io/instance: home-assistant-discovery
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  type: LoadBalancer
  ports:
    - port: 1400
      targetPort: 1400
      protocol: TCP
      name: discovery
  selector:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: home-assistant
---