apiVersion: v1
kind: Service
metadata:
  name: grocy
  labels:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy
spec:
  type: ClusterIP
  clusterIP: 10.43.1.48
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: grocy
    app.kubernetes.io/instance: grocy