apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0                 # The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # The number of pods that can be unavailable during the update process
    type: RollingUpdate           # New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/instance: immich
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.117.0
          ports: 
            - containerPort: 3001
          env:
            - name: IMMICH_MACHINE_LEARNING_URL 
              valueFrom: 
                configMapKeyRef:
                  name: immich
                  key: machine_learning_url
            - name: IMMICH_PORT
              valueFrom: 
                configMapKeyRef:
                  name: immich
                  key: web_port
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: immich
                  key: db_password
            - name: "DB_USERNAME"
              valueFrom:
                configMapKeyRef:
                  name: immich
                  key: db_user
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: immich
                  key: db_name
            - name: DB_HOSTNAME
              valueFrom: 
                configMapKeyRef:
                  name: immich
                  key: db_hostname
            - name: REDIS_HOSTNAME
              valueFrom: 
                configMapKeyRef:
                  name: immich
                  key: redis_hostname
          volumeMounts:
            - name: immich-nfs
              mountPath: "/usr/src/app/upload"
      volumes:
        - name: immich-nfs
          nfs: 
            server: unraid.cosmonautical.cloud
            path: /mnt/user/immich