apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
spec:
  type: ClusterIP
  clusterIP: 10.43.1.44
  ports:
    - port: 2283
      targetPort: 2283
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
