apiVersion: batch/v1
kind: Job
metadata:
  name: bazarr-sync-movies
spec:
  template:
    spec:
          containers:
          - name: bazarr-sync
            image: ghcr.io/ajmandourah/bazarr-sync
            command:
              - /bin/sh
              - -c
              - bazarr-sync --config /usr/src/app/config.yaml sync movies;
            volumeMounts:
              - name: bazarr-sync
                mountPath: /usr/src/app/config.yaml
                subPath: config.yaml
              - name: tvshows
                mountPath: /tvshows
              - name: movies
                mountPath: /movies

          volumes:
            - name: bazarr-sync
              secret:
                secretName: bazarr-sync
            - name: tvshows
              nfs:
                server: unraid.cosmonautical.cloud
                path: /mnt/user/tvshows
            - name: movies
              nfs:
                server: unraid.cosmonautical.cloud
                path: /mnt/user/movies
          restartPolicy: never
---