apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  type: ClusterIP
  clusterIP: 10.43.1.31
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr