apiVersion: v1
kind: Service
metadata:
  name: esphome
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/instance: esphome
spec:
  type: ClusterIP
  clusterIP: 10.43.1.43
  ports:
    - port: 6052
      targetPort: 6052
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/instance: esphome