apiVersion: v1
kind: Service
metadata:
  name: ansible-semaphore
  labels:
    app.kubernetes.io/name: ansible-semaphore
    app.kubernetes.io/instance: ansible-semaphore
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: ansible-semaphore
    app.kubernetes.io/instance: ansible-semaphore
---
