apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
spec:
  type: ClusterIP
  clusterIP: 10.43.1.36
  ports:
    - port: 6767
      targetPort: 6767
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
