apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: jellyfin
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      # I think this will allow Jellyfin to more easily communicate with the TV tuner devices?
      hostNetwork: true
      containers:
        - name: jellyfin
          securityContext:
            privileged: true
            sysctls:
              - name: fs.inotify.max_user_watches
                value: 524288
          image: jellyfin/jellyfin:10.10.2
          ports:
            - containerPort: 8096
          env:
            - name: TZ
              value: "America/Chicago"
            - name: JELLYFIN_CACHE_DIR
              value: "/tmp"
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: tmp
              mountPath: "/tmp"
            - name: zap2it
              mountPath: /media/xmltv 
            - name: tvshows
              mountPath: /media/tvshows
            - name: movies
              mountPath: /media/movies
            - name: audiobooks
              mountPath: /media/audiobooks
            - name: books
              mountPath: /media/books 
            - name: music
              mountPath: /media/music

          lifecycle:
            postStart:
              exec:
                command: 
                  - "/bin/sh"
                  - "-c"
                  - "cd /tmp && apt-get update && \
                    apt-get install -y git && \
                    git clone https://github.com/anultravioletaurora/Jellynautical.git &&\
                    mv ./Jellynautical/min/*.min.css /jellyfin/jellyfin-web/"
    
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 240
            periodSeconds: 30
                  
          resources:
            limits:
              cpu: 4
              memory: "14Gi"
              nvidia.com/gpu: "1" 
            requests:
              cpu: 4
              memory: "14Gi" 
              nvidia.com/gpu: "1"

        - name: jellysearch
          image: domistyle/jellysearch
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          env:
            - name: JELLYFIN_URL
              valueFrom: 
                configMapKeyRef:
                  name: jellyfin-cm
                  key: jellyfin_local_url
            - name: MEILI_URL
              valueFrom:
                configMapKeyRef:
                  name: jellyfin-cm
                  key: meili-url
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyfin
                  key: meili-key
            - name: INDEX_CRON
              valueFrom:
                configMapKeyRef:
                  key: jellysearch-cron
                  name: jellyfin-cm

        - name: meilisearch
          image: getmeili/meilisearch:v1.9
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: meili
              mountPath: "/meili_data"
              subPath: "meilisearch"
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: jellyfin
                  key: meili-key

   
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin
        - name: tmp
          emptyDir:
            medium: Memory
        - name: zap2it
          persistentVolumeClaim:
            claimName: zap2it 
        - name: meili
          persistentVolumeClaim:
            claimName: jellyfin-meili
        - name: movies
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/movies
        - name: tvshows
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/tvshows
        - name: audiobooks
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/audiobooks
        - name: books
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/books
        - name: music
          nfs:
            server: unraid.cosmonautical.cloud
            path: /mnt/user/music
