apiVersion: v1
kind: ConfigMap
metadata:
  name: valheim-cm
data:
  prestart.sh: |
    #!/bin/bash
    # VALHEIM_ASSEMBLY="assembly_valheim.dll"
    # echo "Loading $VALHEIM_ASSEMBLY from /config"
    # cp -v /config/$VALHEIM_ASSEMBLY /opt/valheim/server/valheim_server_Data/Managed

    apt update && apt install apt-transport-https gnupg2 -y;

    wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Debian_12/Release.key -O - | gpg --dearmor | tee /etc/apt/trusted.gpg.d/owncloud-client.gpg > /dev/null;

    echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Debian_12/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud-client.list;

    apt update && apt install owncloud-client -y && echo "Installed Owncloud Client";

  CharacterTemplate.yml: |
    items:
      Wood: 50
      Stone: 30
      
    skills:
      Bows: 15
      Run: 20

  server_name: Cosmonautical
  world_name: Urðarbrunnr
