apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
  labels:
    app.kubernetes.io/name: valheim
    app.kubernetes.io/instance: valheim
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: valheim
      app.kubernetes.io/instance: valheim
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valheim
        app.kubernetes.io/instance: valheim
    spec:
      containers:
        - name: valheim
          image: ghcr.io/lloesche/valheim-server
          imagePullPolicy: Always
          ports: 
            - containerPort: 2456
              protocol: UDP
            - containerPort: 2457
              protocol: UDP
          env: 
            - name: BEPINEX
              value: "true"
            - name: SERVER_PUBLIC
              value: "false"
            - name: UPDATE_CRON
              value: "" # Disables when empty
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: server_name
                  name: valheim-cm
            - name: PRE_START_HOOK
              value: "/config/prestart.sh"                
            - name: WORLD_NAME
              valueFrom:
                configMapKeyRef:
                  key: world_name
                  name: valheim-cm
            - name: "SERVER_PASS"
              valueFrom:
                secretKeyRef:
                  name: valheim
                  key: server_password
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 2
              memory: 8Gi
          volumeMounts:
            - name: config
              mountPath: "/config"
              subPath: "valheim"
            - name: data
              mountPath: "/opt/valheim"
            - name: valheim-cm
              mountPath: "/config/prestart.sh"
              subPath: prestart.sh
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: valheim-data
        - name: valheim-cm
          configMap:
            name: valheim-cm
            defaultMode: 0555
        - name: config
          persistentVolumeClaim:
            claimName: valheim-config
