apiVersion: v1
kind: Service
metadata:
  name: valheim
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
  labels:
    app.kubernetes.io/name: valheim
    app.kubernetes.io/instance: valheim
spec:
  type: LoadBalancer
  ports:
    - port: 2456
      targetPort: 2456
      protocol: UDP
      name: valheim
    - port: 2457
      targetPort: 2457
      protocol: UDP
      name: valheim-steam
  selector:
    app.kubernetes.io/name: valheim
    app.kubernetes.io/instance: valheim
---
