apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app.kubernetes.io/name: busybox
    app.kubernetes.io/instance: busybox
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: busybox
      app.kubernetes.io/instance: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox
        app.kubernetes.io/instance: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command: 
            - /bin/sh
            - "-c"
            - "sleep infinity"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
          volumeMounts:
            - name: auth
              mountPath: "/run/mount/auth"
            - name: cosmonautical
              mountPath: "/run/mount/cosmonautical"
      volumes:
        - name: auth
          persistentVolumeClaim:
            claimName: authentik-db
        - name: cosmonautical
          nfs:
            server: unraid.cosmonautical.cloud
            path: "/mnt/user/cosmonautical"