apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1                 # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1           # < The number of pods that can be unavailable during the update process
    type: RollingUpdate           # < New pods are added gradually, and old pods are terminated gradually
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: ollama
    spec:
      runtimeClassName: nvidia
      containers:
        - name: ollama
          image: ollama/ollama:0.3.12
          ports:
            - containerPort: 11434
          env:
            - name: CUDA_VISIBLE_DEVICES
              value: all
            - name: CUDA_DRIVER_CAPABILITIES
              value: all
          volumeMounts:
            - mountPath: "/root/.ollama"
              name: ollama
              subPath: "ollama"
          resources:
            limits:
              nvidia.com/gpu: '1'

      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
---
