apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  type: ClusterIP
  clusterIP: 10.43.1.81
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama