apiVersion: v1
kind: Service
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui