apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-assets
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: harvester  
---