apiVersion: v1
kind: Service
metadata:
  name: immich-db
  labels:
    app.kubernetes.io/name: immich-db
    app.kubernetes.io/instance: immich-db
spec:
  type: ClusterIP
  clusterIP: 10.43.1.46
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    app.kubernetes.io/name: immich-db
    app.kubernetes.io/instance: immich-db
