apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1                 # The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 2           # The number of pods that can be unavailable during the update process
    type: RollingUpdate           # New pods are added gradually, and old pods are terminated gradually
  replicas: 3 
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:15.7-bookworm"
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          volumeMounts: 
            - name: postgres
              mountPath: "/var/lib/postgresql/data"
              subPath: data
        - name: redis
          image: redis:7.4.0
          ports: 
            - containerPort: 6379
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres