apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 100Gi
  storageClassName: harvester  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: harvester  